services:
  zookeeper:
    image: bitnami/zookeeper:3.8.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: |
        bash -c "echo ruok | nc localhost 2181"
      interval: 10s
      timeout: 5s
      retries: 5
  kafka:
    image: bitnami/kafka:3.4.1
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka-1:9092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - kafka_data:/bitnami/kafka
    depends_on:
      zookeeper:
        condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agentpw
      POSTGRES_DB: agent_scoring
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent -d agent_scoring || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  create-bucket:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      set -e; \
      until mc alias set local http://minio:9000 minio minio123; do echo 'waiting for minio...'; sleep 2; done; \
      mc mb -p local/ccas-audio-dev || true; \
      mc anonymous set download local/ccas-audio-dev/raw || true; \
      echo 'bucket ready'; \
      sleep 2"

  create-kafka-topics:
    image: bitnami/kafka:3.4.1
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      echo 'Creating Kafka topics...'; \
      kafka-topics.sh --bootstrap-server kafka-1:9092 --create --if-not-exists --topic calls.raw --partitions 3 --replication-factor 1; \
      kafka-topics.sh --bootstrap-server kafka-1:9092 --create --if-not-exists --topic calls.enriched --partitions 3 --replication-factor 1; \
      kafka-topics.sh --bootstrap-server kafka-1:9092 --create --if-not-exists --topic audio.ready --partitions 3 --replication-factor 1; \
      kafka-topics.sh --bootstrap-server kafka-1:9092 --create --if-not-exists --topic audio.ready.dlq --partitions 3 --replication-factor 1; \
      echo 'Kafka topics created successfully'; \
      "

  run-migrations:
    build: .
    command: alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=agent_scoring
      - DB_USER=agent
      - DB_PASSWORD=agentpw
    volumes:
      - .:/usr/src/app

  avaya-mock:
    build: .
    command: uvicorn avaya.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app

  ingestion-scheduler:
    build: .
    command: python -m app.services.ingestion_scheduler
    depends_on:
      kafka:
        condition: service_healthy
      avaya-mock:
        condition: service_started
    env_file: .env
    environment:
      - KAFKA_BOOTSTRAP=kafka-1:9092
      - AVAYA_BASE_URL=http://avaya-mock:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "9100:9100"

  metadata-enricher:
    build: .
    command: python -m app.services.metadata_enricher
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      run-migrations:
        condition: service_completed_successfully
    env_file: .env
    environment:
      - DB_HOST=postgres
      - KAFKA_BOOTSTRAP=kafka-1:9092
    volumes:
      - .:/usr/src/app

  audio-downloader:
    build: .
    command: python -m app.services.audio_downloader
    depends_on:
      kafka:
        condition: service_healthy
      minio:
        condition: service_healthy
    env_file: .env
    environment:
      - KAFKA_BOOTSTRAP=kafka-1:9092
      - S3_ENDPOINT=http://minio:9000
    volumes:
      - .:/usr/src/app
    ports:
      - "9200:9200"

  stt-consumer:
    build: .
    command: python -m app.services.stt_consumer
    depends_on:
      kafka:
        condition: service_healthy
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      - STT_MAX_WORKERS=4
      - DB_POOL_SIZE=10
      - WHISPER_DEVICE=cpu
      - WHISPER_MODEL_SIZE=base
      - DB_HOST=postgres
      - KAFKA_BOOTSTRAP=kafka-1:9092
      - S3_ENDPOINT=http://minio:9000
    volumes:
      - .:/usr/src/app
    deploy:
      replicas: 2  # Run 2 instances by default
    mem_limit: 8g
    cpus: 6.0

  dlq-consumer:
    build: .
    command: python -m app.services.dlq_consumer
    depends_on:
      kafka:
        condition: service_healthy
    env_file: .env
    environment:
      - KAFKA_BOOTSTRAP=kafka-1:9092
    volumes:
      - .:/usr/src/app

volumes:
  pgdata:
  minio_data:
  kafka_data:
