"""Add processed_at field to call table

Revision ID: 202509151700_add_processed_at
Revises: 202509151600_stt_schema
Create Date: 2025-09-15 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '202509151700_add_processed_at'
down_revision = '202509151600_stt_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call', 'processed_at')
    # ### end Alembic commands ###